/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "surface-container-highest": "#353534",
        "tertiary-container": "#e364a7",
        "primary-fixed": "#e1e0ff",
        "on-secondary-container": "#00424e",
        "surface": "#131313",
        "surface-container-low": "#1c1b1b",
        "secondary": "#4cd7f6",
        "surface-container": "#201f1f",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-fixed-dim": "#c0c1ff",
        "surface-dim": "#131313",
        "primary-container": "#8083ff",
        "on-tertiary-container": "#560038",
        "outline-variant": "#464554",
        "inverse-primary": "#494bd6",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-fixed": "#001f26",
        "on-primary-fixed": "#07006c",
        "background": "#131313",
        "tertiary-fixed": "#ffd8e7",
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "on-surface": "#e5e2e1",
        "tertiary": "#ffafd3",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "outline": "#908fa0",
        "on-error": "#690005",
        "on-tertiary": "#620040",
        "error-container": "#93000a",
        "on-secondary": "#003640",
        "on-tertiary-fixed": "#3d0026",
        "secondary-container": "#03b5d3",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffafd3",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "surface-tint": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "primary": "#c0c1ff",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#85145a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "section-gap-desktop": "160px",
        "section-gap-mobile": "80px",
        "base": "8px",
        "margin-page": "40px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-xl": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
